apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodeclass
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ipnextgen/sample-eks-ami-gitops-pipeline.git
    targetRevision: main
    path: karpenter-configs/clusters/eks-ami-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
